version: "3.8"
services:
  web:
    build: .
    command: bash -c "bundle exec rspec && bundle exec cucumber"
    volumes:
      - .:/code/right_http_connection
    ports:
        - 8081:80
        - 443:443
